spring:
  datasource:
    url: jdbc:postgresql://shuttle.proxy.rlwy.net:24301/railway
    username: postgres
    password: JvklzxmYUeNshCraWQsrofhBNOgQyPMd
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000  # 10 seconds
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000        # 30 seconds
      max-lifetime: 60000        # 1 minute - shorter than typical DB server timeout
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000   # 5 seconds
      initialization-fail-timeout: -1  # Try to reconnect indefinitely
  
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true  # Helps with LazyInitializationException
  # datasource:
  #   url: jdbc:h2:file:./data/workshop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #   username: sa
  #   password: 
  #   driver-class-name: org.h2.Driver

external:
  externalUrl: https://damp-lynna-wsep-1984852e.koyeb.app/

startup:
  initFile: empty_init.txt
  # empty_init.txt
  # init.txt
  defaultSystemManager:
    name: idan
    password: 1234