spring:
  datasource:
    url: jdbc:postgresql://shuttle.proxy.rlwy.net:24301/railway
    username: postgres
    password: JvklzxmYUeNshCraWQsrofhBNOgQyPMd
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000        # Reduced to 5 seconds for faster startup
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 60000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
      initialization-fail-timeout: 0  # CRITICAL: This allows app to start even if DB is down
      connection-init-sql: SELECT 1   # Simple validation query
    
    # Add these critical properties
    continue-on-error: true           # Continue application startup even if datasource fails

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none                  # Don't try to modify DB schema on startup
      
  # datasource:
  #   url: jdbc:h2:file:./data/workshop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #   username: sa
  #   password: 
  #   driver-class-name: org.h2.Driver

external:
  externalUrl: https://damp-lynna-wsep-1984852e.koyeb.app/

startup:
  initFile: empty_init.txt
  # empty_init.txt
  # init.txt
  defaultSystemManager:
    name: idan
    password: 1234