spring:
  datasource:
    url: jdbc:h2:file:./data/shop_system;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver

external:
  externalUrl: https://damp-lynna-wsep-1984852e.koyeb.app/

startup:
  initFile: init.txt
