spring:
  datasource:
    url: jdbc:postgresql://shuttle.proxy.rlwy.net:24301/railway
    username: postgres
    password: JvklzxmYUeNshCraWQsrofhBNOgQyPMd
    driver-class-name: org.postgresql.Driver

external:
  externalUrl: https://damp-lynna-wsep-1984852e.koyeb.app/

startup:
  initFile: empty_init.txt
  # empty_init.txt
  # init.txt
  defaultSystemManager:
    name: idan
    password: 1234